Repository streamnative/pulsar-resources-operator, pull requests merged in 2024-09, with the labels that each got.

#246 Update resource operator documentation
  README.md
  api/v1alpha1/common.go
  api/v1alpha1/pulsarconnection_types.go
  api/v1alpha1/pulsarnamespace_types.go
  api/v1alpha1/pulsarpermission_types.go
  api/v1alpha1/pulsartenant_types.go
  api/v1alpha1/pulsartopic_types.go
  docs/pulsar_connection.md
  docs/pulsar_geo_replication.md
  docs/pulsar_namespace.md
  docs/pulsar_permission.md
  docs/pulsar_resource_lifecycle.md
  docs/pulsar_tenant.md
  docs/pulsar_topic.md
Labels: doc-info-missing

#248 add replication cluster to pulsar topic resource
  api/v1alpha1/pulsartopic_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/resource.streamnative.io_pulsarconnections.yaml
  config/crd/bases/resource.streamnative.io_pulsarfunctions.yaml
  config/crd/bases/resource.streamnative.io_pulsargeoreplications.yaml
  config/crd/bases/resource.streamnative.io_pulsarnamespaces.yaml
  config/crd/bases/resource.streamnative.io_pulsarpackages.yaml
  config/crd/bases/resource.streamnative.io_pulsarpermissions.yaml
  config/crd/bases/resource.streamnative.io_pulsarsinks.yaml
  config/crd/bases/resource.streamnative.io_pulsarsources.yaml
  config/crd/bases/resource.streamnative.io_pulsartenants.yaml
  config/crd/bases/resource.streamnative.io_pulsartopics.yaml
  docs/pulsar_topic.md
  pkg/admin/impl.go
  pkg/connection/reconcile_namespace.go
  pkg/connection/reconcile_topic.go
Labels: doc-info-missing

#247 chore: upgrade controller-runtime
  controllers/suite_test.go
  go.mod
  go.sum
  go.work.sum
Labels: no-need-doc

#250 feat: support ns offload policy
  .golangci.yml
  api/v1alpha1/pulsarnamespace_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  docs/pulsar_namespace.md
  go.mod
  go.sum
  go.work.sum
  pkg/admin/impl.go
  pkg/admin/interface.go
  pkg/connection/reconcile_namespace.go
  pkg/connection/reconcile_topic.go
  pkg/connection/reconciler.go
  tests/operator/resources_test.go
Labels: doc-required

#236 Delete resources' cr if pulsar cluster doesn't exist
  pkg/admin/errors.go
  pkg/connection/reconcile_geo_replication.go
  pkg/connection/reconcile_namespace.go
  pkg/connection/reconcile_tenant.go
  pkg/connection/reconcile_topic.go
Labels: no-need-doc

#252 feat: add retry count var
  main.go
Labels: doc-required

#251 feat: add the operator resync duration var
  main.go
Labels: doc-required

#253 chore: upgrade chart to 0.6
  charts/pulsar-resources-operator/Chart.yaml
  charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsarconnections.yaml
  charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsarfunctions.yaml
  charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsargeoreplications.yaml
  charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsarnamespaces.yaml
  charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsarpackages.yaml
  charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsarpermissions.yaml
  charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsarsinks.yaml
  charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsarsources.yaml
  charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsartenants.yaml
  charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsartopics.yaml
  charts/pulsar-resources-operator/templates/deployment.yaml
  charts/pulsar-resources-operator/tests/deployment_test.yaml
  charts/pulsar-resources-operator/values.yaml
  config/crd/bases/resource.streamnative.io_pulsarconnections.yaml
  config/crd/bases/resource.streamnative.io_pulsarfunctions.yaml
  config/crd/bases/resource.streamnative.io_pulsargeoreplications.yaml
  config/crd/bases/resource.streamnative.io_pulsarnamespaces.yaml
  config/crd/bases/resource.streamnative.io_pulsarpackages.yaml
  config/crd/bases/resource.streamnative.io_pulsarpermissions.yaml
  config/crd/bases/resource.streamnative.io_pulsarsinks.yaml
  config/crd/bases/resource.streamnative.io_pulsarsources.yaml
  config/crd/bases/resource.streamnative.io_pulsartenants.yaml
  config/crd/bases/resource.streamnative.io_pulsartopics.yaml
Labels: no-need-doc

#254 fix cve 2024-34156
  .github/workflows/e2e_test.yml
  Dockerfile
  go.mod
  go.work
  redhat.Dockerfile
  tests/go.mod
Labels: doc-info-missing

#257 optimize the controller reconcile
  pkg/connection/reconcile_function.go
  pkg/connection/reconcile_geo_replication.go
  pkg/connection/reconcile_package.go
  pkg/connection/reconcile_permission.go
  pkg/connection/reconcile_sink.go
  pkg/connection/reconcile_source.go
  pkg/connection/reconcile_tenant.go
Labels: no-need-doc
