Repository streamnative/pulsar-resources-operator, pull requests merged in 2025-04, with the labels that each got.

#302 Bump golang to 1.23, Alpine to 3.21, golang.org/x/net and github.com/golang-jwt/jwt/v5 to latest to address CVEs
  .github/workflows/e2e_test.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/release-operator.yml
  .github/workflows/style.yml
  .golangci.yml
  Dockerfile
  go.mod
  go.sum
  go.work
  redhat.Dockerfile
  tests/go.mod
  tests/go.sum
Labels: no-need-doc

#304 chore: bump the operator to 0.9.2
  charts/pulsar-resources-operator/Chart.yaml
Labels: no-need-doc

#306 fix dockerhub login in ci
  .github/workflows/e2e_test.yml
Labels: doc-info-missing

#295 Fixes #288 - Operator does not revoke permissions when roles get removed from the list
  CONTRIBUTING.md
  pkg/admin/dummy.go
  pkg/admin/impl.go
  pkg/admin/interface.go
  pkg/connection/reconcile_permission.go
  tests/README.md
  tests/operator/operator_suite_test.go
  tests/operator/resources_test.go
  tests/utils/spec.go
Labels: no-need-doc

#301 Feature/tlsauth
  api/v1alpha1/common.go
  api/v1alpha1/pulsarconnection_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/resource.streamnative.io_pulsarconnections.yaml
  docs/pulsar_connection.md
  pkg/admin/interface.go
  pkg/connection/reconciler.go
Labels: doc

#184 feat: support TLS authentication and customized volumes
  charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsarconnections.yaml
  charts/pulsar-resources-operator/templates/deployment.yaml
  charts/pulsar-resources-operator/tests/deployment_test.yaml
  charts/pulsar-resources-operator/values.yaml
Labels: no-need-doc
